name: koi-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - pandas
      - numpy
      - catboost
      - lightgbm
      - altair
      - seaborn
      - matplotlib
      - scikit-learn
      - autogluon.tabular[mitra]

